### PR TITLE
Apply base64 to allow binary job contents

### LINKED ISSUE #188: Allow binary data for job contents
Currently, it is impossible to put binary data in a job. `unserialize` will work fine with this, and correctly serialize this data. However, `json_encode` will give the following error:

```
Malformed UTF-8 characters, possibly incorrectly encoded
```

### PR DESCRIPTION
**Pull request by kokx**
This applies base64 to allow job contents with binary data. So together with @roelvanduijnhoven I came up with this solution.

This PR does break some compatibility, since older jobs will not be compatible to be deserialized. We might work on a backwards-compatible solution for this later. Probably something that checks first if the content probably is base64-encoded or not.

Fixes #188

### CODE REVIEW

**Comment by kokx** [comment]
I removed the binary data from the `QueueTest`. Thanks for pointing me in the right direction there!

**Comment by kokx** [comment]
Reworked the PR in accordance with the ideas given in #188

**Comment by basz** [comment]
thanks @kokx could you please add a note to the documentation? Then I shall merge and release 0.7.0

**Comment by kokx** [comment]
@basz I've added some documentation.

**Comment by basz** [comment]
Thanks! I'll have merged, and I'll release tonight

**Pull request merged**
