### PR TITLE
Fix for composer php version including 7.0

### PR DESCRIPTION
**Pull request by TomHAnderson**

### CODE REVIEW

**Comment by basz** [comment]
Hi Tom! What is this supposed to fix? Both notations allow for php7?

**Comment by TomHAnderson** [comment]
^5.5 fails for 5.6.

```
composer require slm/queue-doctrine
Using version ^0.6.1 for slm/queue-doctrine
./composer.json has been updated
Loading composer repositories with package information
Updating dependencies (including require-dev)
Your requirements could not be resolved to an installable set of packages.

  Problem 1
    - This package requires php ^7.0 but your PHP version (5.6.20) does not satisfy that requirement.
```

**Comment by TomHAnderson** [comment]
The annotation for ^5.5 resolves to 7.0, I believe, and that's why we need ~5.3 || ^7.0 
It'd be great to get these fixes in right away as I'm about to use Slm on yet another project.

**Comment by basz** [comment]
you mean `>=5.5` fails on 5.6?. https://github.com/juriansluiman/SlmQueue/blob/master/composer.json#L25 that's weird...

AFAIK tag should become `^5.5 || ^7.0` which should work on 5.5, 5.6, 7.0, 7.1.

**Comment by basz** [comment]
but this always confuses the hell outa me...

here is test '>=1.0' which selects what i would expect : 
https://semver.mwl.be/#?package=bushbaby%2Fflysystem&version=%3E%3D1.0&minimum-stability=stable

here is test '^1.0' which also selects what i would expect : 
https://semver.mwl.be/#?package=bushbaby%2Fflysystem&version=%5E1.1&minimum-stability=stable

**Comment by TomHAnderson** [comment]
I'll investigate that error a little more, brb

**Comment by basz** [comment]
if you would please. FYI I can run `mkdir test && cd test && composer require slm/queue-doctrine` without problems using php56

**Comment by TomHAnderson** [comment]
This was not a problem with slm.  This was my problem for restricting PHP on my application composer.json and composer not telling me which package (the root one) required 7.0.  I found this when I tried to install slm and saw the message.

**Pull request closed without merging**
