### PR TITLE
Do not require shared event manager if it not exists

### PR DESCRIPTION
**Pull request by svycka**
This allows using this module without zend-mvc.

### CODE REVIEW

**Comment by svycka** [comment]
@basz I think this way we will avoid BC break

**Comment by basz** [comment]
yep, how 'bout this https://github.com/juriansluiman/SlmQueue/blob/master/composer.json#L35 we can't move it to suggested without BC. Why is it in require-dev anyway?

**Comment by svycka** [comment]
I think if you use it with zend-mvc you still need this for controller and routes... also controllers should be tested not sure if they are :)

**Comment by basz** [comment]
Hi, are you able to test if the controllers are still compatible? If not I tag the next major version.

**Comment by svycka** [comment]
Should work and we have tests to confirm this so I guess it's ok

**Comment by svycka** [comment]
but for next major version I would go with symfony/console

**Comment by basz** [comment]
sure why not, you have time to do that?

**Comment by svycka** [comment]
don't have time now but when I have time why not unless you need it now.

**Comment by basz** [comment]
i don't have a need for it at this time, I don't really care bout which console to use.. :) But the cereal idea of decoupling as much as possible I like... so whenever to got time... Are you waiting on a tag with this PR in it?

**Comment by svycka** [comment]
I somehow workarounded this but yes tag would be nice :smile:

**Pull request merged**
